// Code generated by tygo. DO NOT EDIT.
// AUTO-GENERATED by tygo from server-go/internal/dto — DO NOT EDIT

//////////
// source: agent.go

/**
 * Agent represents a ship in the internal server model
 */
export interface Agent {
  id: string;
  ownerId: string;
  name: string;
  state: AgentState;
  positionX: number /* float64 */;
  positionY: number /* float64 */;
  positionZ: number /* float64 */;
  homeX: number /* float64 */;
  homeY: number /* float64 */;
  homeZ: number /* float64 */;
  targetX?: number /* float64 */;
  targetY?: number /* float64 */;
  targetZ?: number /* float64 */;
  startPositionX?: number /* float64 */;
  startPositionY?: number /* float64 */;
  startPositionZ?: number /* float64 */;
  wanderDirX: number /* float64 */;
  wanderDirY: number /* float64 */;
  wanderDirZ: number /* float64 */;
  wanderPhase: number /* float64 */;
  targetSpaceId?: string;
  currentSpaceId?: string;
  travelStartTime?: number /* int64 */;
  travelDuration?: number /* int64 */;
  spacesDiscovered: number /* int */;
  distanceTraveled: number /* float64 */;
  createdAt: number /* int64 */;
  deployedAt?: number /* int64 */;
  /**
   * Masterplan 2026 fields
   */
  currentPointsPerMin: number /* float64 */;
  totalAgiEarned: number /* float64 */;
  autopilotEnabled: boolean;
  shipType: string;
}
/**
 * ShipDTO represents a ship for the client (mapped from Agent)
 */
export interface ShipDTO {
  id: string;
  ownerId: string;
  name: string;
  state: ShipState;
  shipType: string;
  positionX: number /* float64 */;
  positionY: number /* float64 */;
  positionZ: number /* float64 */;
  startPositionX?: number /* float64 */;
  startPositionY?: number /* float64 */;
  startPositionZ?: number /* float64 */;
  targetPositionX?: number /* float64 */;
  targetPositionY?: number /* float64 */;
  targetPositionZ?: number /* float64 */;
  currentSynapseId?: string;
  travelStartTime?: number /* int64 */;
  travelDuration?: number /* int64 */;
  rotationY?: number /* float64 */; // Yaw rotation in radians - direction ship is facing
  autopilotEnabled: boolean;
  autopilotPreferences?: AutopilotPreferences;
  equippedItems: EquippedItem[];
  currentPointsPerMin: number /* float64 */;
  spacesDiscovered: number /* int */;
  totalAgiEarned: number /* float64 */;
  createdAt: number /* int64 */;
}
/**
 * AgentCluster represents a cluster of agents for LOD visualization
 */
export interface AgentCluster {
  id: string;
  lodLevel: number /* int */;
  positionX: number /* float64 */;
  positionY: number /* float64 */;
  positionZ: number /* float64 */;
  agentCount: number /* int */;
  dominantState: AgentState;
  avgProgress: number /* float64 */;
  updatedAt: number /* int64 */;
}
/**
 * ShipCluster represents a cluster of ships for the client
 */
export interface ShipCluster {
  id: string;
  lodLevel: number /* int */;
  positionX: number /* float64 */;
  positionY: number /* float64 */;
  positionZ: number /* float64 */;
  shipCount: number /* int */;
  dominantState: ShipState;
  avgProgress: number /* float64 */;
  updatedAt: number /* int64 */;
}
/**
 * AgentUpdate represents a partial agent update for WebSocket broadcast
 */
export interface AgentUpdate {
  id: string;
  positionX: number /* float64 */;
  positionY: number /* float64 */;
  positionZ: number /* float64 */;
  state: AgentState;
  targetSpaceId?: string;
  travelStartTime?: number /* int64 */;
  travelDuration?: number /* int64 */;
}
/**
 * EquippedItem represents an item equipped to a ship
 */
export interface EquippedItem {
  itemId: string;
  itemType: string;
  slotIndex: number /* int */;
  equippedAt: number /* int64 */;
  expiresAt?: number /* int64 */;
}
/**
 * AutopilotPreferences represents ship autopilot settings
 */
export interface AutopilotPreferences {
  preferredSynapseTypes: SynapseType[];
  maxPointsPerMin: number /* float64 */;
  avoidCrowded: boolean;
}

//////////
// source: brain_part.go

/**
 * BrainPartDTO is the API representation of a brain part
 * tygo: BrainPartDTO
 */
export interface BrainPartDTO {
  id: string;
  name: string;
  displayName: string;
  description: string;
  centerX: number /* float64 */;
  centerY: number /* float64 */;
  centerZ: number /* float64 */;
  radius: number /* float64 */;
  colorR: number /* float64 */;
  colorG: number /* float64 */;
  colorB: number /* float64 */;
  isEnabled: boolean;
  sortOrder: number /* int */;
}

//////////
// source: config.go

/**
 * UserLevelConfig represents configuration for a user level
 */
export interface UserLevelConfig {
  minUSDC: number /* float64 */;
  multiplier: number /* float64 */;
  maxShips: number /* int */;
  label: string;
}
/**
 * WorldBounds represents the brain boundaries
 */
export interface WorldBounds {
  min: number /* float64 */;
  max: number /* float64 */;
  boundaryMargin: number /* float64 */;
  boundarySteerStrength: number /* float64 */;
}
/**
 * TraitEffect represents the effect of a trait on ship behavior
 */
export interface TraitEffect {
  type: string;
  speedBonus?: number /* float64 */;
  burnPenalty?: number /* float64 */;
  burnReduction?: number /* float64 */;
  speedPenalty?: number /* float64 */;
  discoveryBonus?: number /* float64 */;
  solvePenalty?: number /* float64 */;
  lootBonus?: number /* float64 */;
  luckyChance?: number /* float64 */;
  luckyMultiplier?: number /* float64 */;
  collaborativeBonus?: number /* float64 */;
}
/**
 * GameConfigForFrontend matches the frontend GameConfig interface
 */
export interface GameConfigForFrontend {
  costs: CostConfig;
  rates: RateConfig;
  world: WorldConfig;
  traits: { [key: string]: TraitEffect};
  tiers: TierConfig;
  version: string;
}
/**
 * CostConfig contains cost-related game constants
 */
export interface CostConfig {
  AGENT_BASE_COST: number /* int */;
  TRAIT_COST_PER_LEVEL: number /* int */;
  REPAIR_COST_MULTIPLIER: number /* float64 */;
  STARTING_USER_POINTS: number /* int */;
  STARTING_AGENT_FUEL: number /* int */;
  REPAIR_FUEL_AMOUNT: number /* int */;
}
/**
 * RateConfig contains rate-related game constants
 */
export interface RateConfig {
  TICK_INTERVAL_MS: number /* int */;
  BASE_BURN_RATE: number /* float64 */;
  BASE_SPEED: number /* float64 */;
  BASE_SEARCH_SPEED: number /* float64 */;
  DETECTION_RADIUS: number /* float64 */;
  WANDER_TURN_RATE: number /* float64 */;
}
/**
 * WorldConfig contains world boundary settings
 */
export interface WorldConfig {
  BRAIN_BOUNDS_MIN: number /* float64 */;
  BRAIN_BOUNDS_MAX: number /* float64 */;
  BOUNDARY_MARGIN: number /* float64 */;
  BOUNDARY_STEER_STRENGTH: number /* float64 */;
}
/**
 * TierConfig contains tier/level limits and bonuses
 */
export interface TierConfig {
  limits: { [key: string]: number /* int */};
  stakingBonuses: StakingBonus[];
}
/**
 * StakingBonus represents a staking threshold and bonus
 */
export interface StakingBonus {
  threshold: number /* int */;
  bonus: number /* int */;
}

//////////
// source: ship_type.go

/**
 * ShipTypeDTO is the API representation of a ship type
 * tygo: ShipTypeDTO
 */
export interface ShipTypeDTO {
  id: string;
  name: string;
  displayName: string;
  description: string;
  creationCost: number /* int */;
  speedMultiplier: number /* float64 */;
  solveSpeedMultiplier: number /* float64 */;
  fuelCapacity: number /* int */;
  detectionRadius: number /* float64 */;
  modelFilename?: string;
  isActive: boolean;
  sortOrder: number /* int */;
}

//////////
// source: space.go

/**
 * Space represents a discoverable synapse in the brain
 */
export interface Space {
  id: string;
  positionX: number /* float64 */;
  positionY: number /* float64 */;
  positionZ: number /* float64 */;
  region: BrainRegion;
  zone: string;
  synapseCount: number /* int */;
  state: SpaceState;
  discoveredAt?: number /* int64 */;
  /**
   * Masterplan 2026 fields
   */
  synapseType: SynapseType;
  pointsRequired: number /* int */;
  pointsAccumulated: number /* int */;
  currentEtaMinutes?: number /* float64 */;
  agiReward: number /* float64 */;
  sectorId?: string;
}
/**
 * SpaceCluster represents a cluster of spaces for LOD visualization
 */
export interface SpaceCluster {
  id: string;
  lodLevel: number /* int */;
  positionX: number /* float64 */;
  positionY: number /* float64 */;
  positionZ: number /* float64 */;
  spaceCount: number /* int */; // Server naming
  synapseCount: number /* int */; // Client naming (mapped)
  discoveredCount: number /* int */;
  beingSolvedCount: number /* int */; // Server naming
  beingExploredCount: number /* int */; // Client naming (mapped)
  avgLootPool: number /* float64 */;
  typeCounts: { [key: string]: number /* int */};
  updatedAt: number /* int64 */;
}
/**
 * Synapse represents a synapse for the client
 */
export interface Synapse {
  id: string;
  positionX: number /* float64 */;
  positionY: number /* float64 */;
  positionZ: number /* float64 */;
  region: string;
  zone: string;
  synapseType: SynapseType;
  state: SynapseState;
  synapseCount: number /* int */;
  pointsRequired: number /* int */;
  pointsAccumulated: number /* int */;
  currentEtaMinutes: number /* float64 */;
  explorerCount: number /* int */;
  maxExplorers: number /* int */;
  sectorId?: string;
  explorers?: ExplorerInfo[];
}
/**
 * SpaceDiscovery represents a discovery event
 */
export interface SpaceDiscovery {
  spaceId: string;
  positionX: number /* float64 */;
  positionY: number /* float64 */;
  positionZ: number /* float64 */;
  discoveredBy: string[];
  lootDistribution: LootDistributionItem[];
  timestamp: number /* int64 */;
}
/**
 * LootDistributionItem represents a loot distribution to an agent
 */
export interface LootDistributionItem {
  agentId: string;
  ownerId: string;
  amount: number /* float64 */;
}
/**
 * LootEvent represents a loot distribution event
 */
export interface LootEvent {
  userId: string;
  agentId: string;
  spaceId: string;
  amount: number /* float64 */;
  timestamp: number /* int64 */;
}
/**
 * ExplorerInfo represents information about a synapse explorer
 */
export interface ExplorerInfo {
  shipId: string;
  userId: string;
  shipName: string;
  pointsContributed: number /* float64 */;
  pointsPerMinute: number /* float64 */;
  joinedAt: number /* int64 */;
}

//////////
// source: synapse_type.go

/**
 * SynapseTypeDTO is the API representation of a synapse type
 * tygo: SynapseTypeDTO
 */
export interface SynapseTypeDTO {
  id: string;
  name: string;
  displayName: string;
  colorR: number /* float32 */;
  colorG: number /* float32 */;
  colorB: number /* float32 */;
  etaMinutesMin: number /* int */;
  etaMinutesMax: number /* int */;
  maxPointsPerMin: number /* int */;
  agiRewardMin: number /* int */;
  agiRewardMax: number /* int */;
  modelFilename?: string;
  sortOrder: number /* int */;
}

//////////
// source: types.go

/**
 * SynapseType represents the type of synapse (dynamic, managed via synapse_types table)
 */
export type SynapseType = string;
/**
 * AgentState represents the internal state of an agent/ship
 */
export type AgentState = string;
export const AgentIdle: AgentState = "idle";
export const AgentSearching: AgentState = "searching";
export const AgentTraveling: AgentState = "traveling";
export const AgentSolving: AgentState = "solving";
export const AgentReturning: AgentState = "returning";
/**
 * ShipState represents the client-facing state (mapped from AgentState)
 */
export type ShipState = string;
export const ShipIdle: ShipState = "idle";
export const ShipSearching: ShipState = "searching";
export const ShipTraveling: ShipState = "traveling";
export const ShipSolving: ShipState = "solving"; // was "exploring"
export const ShipReturning: ShipState = "returning";
/**
 * SpaceState represents the state of a space/synapse
 */
export type SpaceState = string;
export const SpaceUndiscovered: SpaceState = "undiscovered";
export const SpaceBeingSolved: SpaceState = "being_solved";
export const SpaceDiscovered: SpaceState = "discovered";
/**
 * SynapseState represents the client-facing synapse state
 */
export type SynapseState = string;
export const SynapseUndiscovered: SynapseState = "undiscovered";
export const SynapseBeingExplored: SynapseState = "being_explored";
export const SynapseCompleted: SynapseState = "completed";
/**
 * UserLevel represents the user's level (1-5)
 */
export type UserLevel = number /* int */;
export const UserLevel1: UserLevel = 1;
export const UserLevel2: UserLevel = 2;
export const UserLevel3: UserLevel = 3;
export const UserLevel4: UserLevel = 4;
export const UserLevel5: UserLevel = 5;
/**
 * UserTier represents the user's tier
 */
export type UserTier = string;
export const TierFree: UserTier = "free";
export const TierBronze: UserTier = "bronze";
export const TierSilver: UserTier = "silver";
export const TierGold: UserTier = "gold";
export const TierPlatinum: UserTier = "platinum";
export const TierDiamond: UserTier = "diamond";
/**
 * BrainRegion represents a region of the brain
 */
export type BrainRegion = string;
export const RegionFrontal: BrainRegion = "frontal";
export const RegionParietal: BrainRegion = "parietal";
export const RegionTemporal: BrainRegion = "temporal";
export const RegionOccipital: BrainRegion = "occipital";
export const RegionCerebellum: BrainRegion = "cerebellum";
export const RegionBrainstem: BrainRegion = "brainstem";

//////////
// source: user.go

/**
 * User represents a user account
 */
export interface User {
  id: string;
  wallet: string;
  tier: UserTier;
  stakedAmount: number /* float64 */;
  points: number /* float64 */;
  totalLootEarned: number /* float64 */;
  createdAt: number /* int64 */;
  /**
   * Masterplan 2026 fields
   */
  userLevel?: UserLevel;
  usdcSpent?: number /* float64 */;
  agenticBalance?: number /* float64 */;
  totalAgiEarned?: number /* float64 */;
  lotteryTickets?: number /* int */;
  maxShips?: number /* int */;
}

//////////
// source: websocket.go

/**
 * ClientMessage represents a message from client to server
 */
export interface ClientMessage {
  type: string;
  data: unknown;
}
/**
 * ClientMessage types
 */
export const ClientMessageTypePing = "ping";
/**
 * ClientMessage types
 */
export const ClientMessageTypeAuthIdentify = "auth:identify";
/**
 * ClientMessage types
 */
export const ClientMessageTypeAuthLogout = "auth:logout";
/**
 * AuthIdentifyData contains auth identification data
 */
export interface AuthIdentifyData {
  token: string;
}
/**
 * ServerMessage represents a message from server to client
 */
export interface ServerMessage {
  type: string;
  data: any;
}
/**
 * ServerMessage types
 */
export const ServerMessageTypeStateSync = "state:sync";
/**
 * ServerMessage types
 */
export const ServerMessageTypeShipsSync = "ships:sync";
/**
 * ServerMessage types
 */
export const ServerMessageTypeAgentsUpdate = "agents:update";
/**
 * ServerMessage types
 */
export const ServerMessageTypeSpaceDiscovered = "space:discovered";
/**
 * ServerMessage types
 */
export const ServerMessageTypeLootDistributed = "loot:distributed";
/**
 * ServerMessage types
 */
export const ServerMessageTypeSynapseCompleted = "synapse:completed";
/**
 * ServerMessage types
 */
export const ServerMessageTypeExplorationProgress = "exploration:progress";
/**
 * ServerMessage types
 */
export const ServerMessageTypeUserLevelUp = "user:levelup";
/**
 * ServerMessage types
 */
export const ServerMessageTypeSynapsesDelta = "synapses:delta";
/**
 * ServerMessage types
 */
export const ServerMessageTypeTravelStarted = "travel:started";
/**
 * ServerMessage types
 */
export const ServerMessageTypeTravelPosition = "travel:position";
/**
 * ServerMessage types
 */
export const ServerMessageTypeClusterUpdate = "cluster:update";
/**
 * ServerMessage types
 */
export const ServerMessageTypeWorldShips = "world:ships";
/**
 * ServerMessage types
 */
export const ServerMessageTypeAuthSuccess = "auth:success";
/**
 * ServerMessage types
 */
export const ServerMessageTypeAuthError = "auth:error";
/**
 * ServerMessage types
 */
export const ServerMessageTypeError = "error";
/**
 * ServerMessage types
 */
export const ServerMessageTypeTeneoPoints = "teneo:points";
/**
 * ServerMessage types
 */
export const ServerMessageTypeTeneoBurn = "teneo:burn";
/**
 * WorldState represents the full world state
 */
export interface WorldState {
  synapseClusters: SpaceCluster[];
  agentClusters: AgentCluster[]; // Server naming
  shipClusters: ShipCluster[]; // Client expects this too
  userShips: ShipDTO[];
  discoveryProgress: DiscoveryProgress;
  timestamp?: number /* int64 */;
}
/**
 * DiscoveryProgress represents discovery statistics
 */
export interface DiscoveryProgress {
  total: number /* int */;
  discovered: number /* int */;
  beingSolved: number /* int */; // Server naming
  beingExplored: number /* int */; // Client naming
}
/**
 * ShipSyncData represents a ship sync message
 */
export interface ShipSyncData {
  ships: ShipDTO[];
  timestamp: number /* int64 */;
}
/**
 * ShipUpdateData represents partial ship updates
 */
export interface ShipUpdateData {
  ships: ShipDTO[];
  timestamp: number /* int64 */;
}
/**
 * SynapseCompletionData represents a synapse completion event
 */
export interface SynapseCompletionData {
  synapseId: string;
  synapseType: SynapseType;
  discoveredAt: number /* int64 */;
  totalExplorers: number /* int */;
  agiReward: number /* float64 */;
  isLottery: boolean;
  winnerId?: string;
  winnerShipId?: string;
}
/**
 * ExplorationProgressData represents exploration progress updates
 */
export interface ExplorationProgressData {
  synapseId: string;
  synapseType: SynapseType;
  pointsAccumulated: number /* float64 */;
  pointsRequired: number /* int */;
  etaMinutes: number /* float64 */;
  explorerCount: number /* int */;
  timestamp: number /* int64 */;
}
/**
 * UserLevelUpData represents a user level up event
 */
export interface UserLevelUpData {
  userId: string;
  newLevel: UserLevel;
  timestamp: number /* int64 */;
}
/**
 * AuthSuccessData represents auth success
 */
export interface AuthSuccessData {
  userId: string;
}
/**
 * AuthErrorData represents auth error
 */
export interface AuthErrorData {
  message: string;
}
/**
 * ErrorData represents a generic error
 */
export interface ErrorData {
  message: string;
}
/**
 * SynapseCompletionEvent for engine callbacks
 */
export interface SynapseCompletionEvent {
  synapseId: string;
  synapseType: SynapseType;
  discoveredAt: number /* int64 */;
  totalExplorers: number /* int */;
  agiReward: number /* float64 */;
  isLottery: boolean;
  winnerId?: string;
  winnerShipId?: string;
  /**
   * Position for visual effects (discovery burst)
   */
  positionX: number /* float64 */;
  positionY: number /* float64 */;
  positionZ: number /* float64 */;
}
/**
 * ExplorationProgressEvent for engine callbacks
 */
export interface ExplorationProgressEvent {
  synapseId: string;
  synapseType: SynapseType;
  pointsAccumulated: number /* float64 */;
  pointsRequired: number /* float64 */;
  etaMinutes: number /* float64 */;
  explorerCount: number /* int */;
  timestamp: number /* int64 */;
  userId?: string;
  userPoints?: number /* float64 */;
}
/**
 * UserLevelUpEvent for engine callbacks
 */
export interface UserLevelUpEvent {
  userId: string;
  newLevel: UserLevel;
  timestamp: number /* int64 */;
}
/**
 * SynapseDelta represents a single synapse state change
 * Uses compact field names for bandwidth efficiency
 */
export interface SynapseDelta {
  i: number /* uint32 */; // Array index (not UUID) matching bulk endpoint order
  s: number /* uint8 */; // 0=undiscovered, 1=being_solved, 2=discovered
}
/**
 * SynapsesDeltaBatch represents a batch of synapse state changes
 */
export interface SynapsesDeltaBatch {
  c: SynapseDelta[];
  t: number /* int64 */;
}
/**
 * TravelStartedEvent is sent when a ship begins traveling to a synapse
 */
export interface TravelStartedEvent {
  shipId: string;
  startPositionX: number /* float64 */;
  startPositionY: number /* float64 */;
  startPositionZ: number /* float64 */;
  targetPositionX: number /* float64 */;
  targetPositionY: number /* float64 */;
  targetPositionZ: number /* float64 */;
  travelStartTime: number /* int64 */;
  travelDuration: number /* int64 */;
  travelCost: number /* float64 */;
  targetSynapseId: string;
}
/**
 * TravelPositionUpdate represents a position/rotation update during travel
 */
export interface TravelPositionUpdate {
  shipId: string;
  positionX: number /* float64 */;
  positionY: number /* float64 */;
  positionZ: number /* float64 */;
  rotationY: number /* float64 */; // Yaw - direction ship is facing
  progress: number /* float64 */; // 0.0 to 1.0
}
/**
 * TravelPositionBatch batches multiple ship updates for efficient transmission
 */
export interface TravelPositionBatch {
  ships: TravelPositionUpdate[];
  timestamp: number /* int64 */;
}
/**
 * ClusterUpdateEvent is sent when a cluster's state counts change (exploration start/stop)
 * This enables immediate dashboard updates without waiting for periodic state:sync
 */
export interface ClusterUpdateEvent {
  clusters: SpaceCluster[];
  timestamp: number /* int64 */;
}
/**
 * WorldShipUpdate represents a single world ship position (ambient or other-user)
 * Uses compact field names for bandwidth efficiency
 */
export interface WorldShipUpdate {
  id: string;
  tp?: string;
  x: number /* float64 */;
  y: number /* float64 */;
  z: number /* float64 */;
  r: number /* float64 */;
  s: number /* int */; // 0=traveling, 1=idle
  /**
   * Trajectory data for client-side interpolation (only when traveling)
   */
  sx?: number /* float64 */;
  sy?: number /* float64 */;
  sz?: number /* float64 */;
  tx?: number /* float64 */;
  ty?: number /* float64 */;
  tz?: number /* float64 */;
  ts?: number /* int64 */;
  td?: number /* int64 */;
}
/**
 * WorldShipsBatch batches multiple world ship updates
 */
export interface WorldShipsBatch {
  ships: WorldShipUpdate[];
  t: number /* int64 */;
}
/**
 * TeneoPointsEvent is sent when Teneo points are synced (on auth or refresh)
 */
export interface TeneoPointsEvent {
  pointsTotal: number;
  linked: boolean;
}
/**
 * TeneoBurnEvent is sent when Teneo points are burned (travel cost)
 */
export interface TeneoBurnEvent {
  amount: number;
  reason: string;
  newBalance: number;
}
