// Re-export agent types (the primary types for the discovery system)
export {
  type BrainRegion,
  type AgentState,
  type SpaceState,
  type TraitType,
  type AgentTrait,
  type Agent,
  type Space,
  type AgentCluster,
  type SpaceCluster,
  type DiscoveryProgress,
  type WorldState,
  type ServerMessage,
  type ClientMessage,
  type SpaceDiscoveryEvent,
  type LootEvent,
  type User,
  type UserTier,
  TIER_LIMITS,
  getAgentLimit,
  TRAIT_EFFECTS,
} from './agent'
